name: cpsc419-final-proj
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - icu=73.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - libuv=1.48.0
  - ncurses=6.4
  - nodejs=20.17.0
  - openssl=3.0.16
  - pip=25.0
  - python=3.11.11
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - blinker==1.9.0
      - click==8.1.8
      - flask==3.1.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - mysql-connector==2.2.9
      - werkzeug==3.1.3
